server:
  port: 9091 # 端口

spring:
  application:
    name: order-service # 应用名称

# 配置 Eureka Server 注册中心
eureka:
  instance:
    prefer-ip-address: true       # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # ip:port
  client:
    service-url:                  # 设置服务注册中心地址
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

# 自定义配置
name: order-service-prod
password: '{cipher}AQBPVrmp7oXKjyRhizfEdg8KLJF9CMcs/lIfCGuzxEGs3qL4kzaU00d2RGXyJr8x8dtChkCcxdGDFllKN1Ok42JnOYZHPzCrLPFeJUAah57tqpOfpH2S8BAsIYIL9F3lGPNmg0T3lBPfn+dzlnflwclwRJYG3U/AFfpGhlh9JZs5g1/C7FoD5K2gPcFVEnwNqq4IMgEaRrVCGC9wU1sDt7ZL5kucd0TDZC/sV2naCsRW9mkQ2p00ANJhMDU8+xaXI+NcvOwjwWY/IAF1Uh3K9MemGAvmuIyL2y5Awk3GIplKI9uq+TTW2zhW8CBe210zQ+snA7sRIxdMIUpZ+GTKhtImKRTi7phrf8hTS4LzDza+yY+kyi20nKwE6/R3SyOdH/4='
